CREATE DATABASE ShoppingOnline;

GO
USE ShoppingOnline;

CREATE TABLE StockBySize(
StockBySizeId INT PRIMARY KEY IDENTITY(1,1),
XS   INT   NOT NULL,
S    INT    NOT NULL,
M    INT    NOT NULL,
L    INT    NOT NULL,
XL   INT   NOT NULL,
XXL  INT  NOT NULL,
XXXL INT NOT NULL,
EU34 INT NOT NULL,
EU35 INT NOT NULL,
EU36 INT NOT NULL,
EU37 INT NOT NULL,
EU38 INT NOT NULL,
EU39 INT NOT NULL,
EU40 INT NOT NULL,
EU41 INT NOT NULL,
EU42 INT NOT NULL,
EU43 INT NOT NULL,
EU44 INT NOT NULL,
EU45 INT NOT NULL,
EU46 INT NOT NULL,
EU47 INT NOT NULL,
EU48 INT NOT NULL,
EU49 INT NOT NULL
);
CREATE TABLE Client(
ClientId INT PRIMARY KEY IDENTITY(1,1),
ClientFullName VARCHAR(50) NOT NULL,
ClientEmail VARCHAR(50) UNIQUE NOT NULL ,
ClientCI VARCHAR(20) NOT NULL,
ClientPhoneNumber VARCHAR(20) NOT NULL,
ClientDepartament VARCHAR(20) NOT NULL,
ClientCity VARCHAR(20) NOT NULL,
ClientAddressBill VARCHAR(50) NOT NULL,
ClientToHome BIT NOT NULL
);
CREATE TABLE Sale(
SaleId INT PRIMARY KEY IDENTITY(1,1),
SaleAmount DECIMAL NOT NULL,
SaleDate DATETIME DEFAULT GETDATE(),
ClientId INT NOT NULL FOREIGN KEY REFERENCES Client(ClientId)
);
CREATE TABLE Departament(
DepartamentId INT PRIMARY KEY IDENTITY(1,1),
DepartamentName VARCHAR(20) NOT NULL,
DepartamentIsTypeShoes BIT NOT NULL,
DepartamentIsDeleted BIT NOT NULL
);
CREATE TABLE Family(
FamilyId INT PRIMARY KEY IDENTITY(1,1),
FamilyName VARCHAR(20) NOT NULL,
FamilyIsDeleted BIT NOT NULL,
DepartamentId INT NOT NULL FOREIGN KEY REFERENCES Departament(DepartamentId)
);
CREATE TABLE Product(
ProductId INT PRIMARY KEY IDENTITY(1,1),
ProductCode NVARCHAR(10) NOT NULL,
ProductName VARCHAR(20) NOT NULL,
ProductDescription VARCHAR(60) NOT NULL,
ProductImage NVARCHAR(MAX) NOT NULL,
ProductGenre VARCHAR(15) NOT NULL,
ProductColor NVARCHAR(50) NOT NULL,
ProductPrice DECIMAL NOT NULL,
ProductIsDeleted BIT NOT NULL,
StockBySizeId INT NOT NULL FOREIGN KEY REFERENCES StockBySize(StockBySizeId),
FamilyId INT NOT NULL FOREIGN KEY REFERENCES Family(FamilyId)
);
CREATE TABLE LineSale(
LineSaleId INT NOT NULL IDENTITY(1,1),
LineSaleProductQuantity INT NOT NULL,
LineSaleProductPrice DECIMAL NOT NULL,
ProductId INT FOREIGN KEY REFERENCES Product(ProductId),
SaleId INT FOREIGN KEY REFERENCES Sale(SaleId),
primary key(LineSaleId, ProductId, SaleId)
);
