CREATE DATABASE ShoppingOnline;

go
USE ShoppingOnline;

CREATE TABLE StockBySize(
StockBySizeId INT PRIMARY KEY IDENTITY(1,1),
XS   NUMBER(5)   NOT NULL,
S    NUMBER(5)    NOT NULL,
M    NUMBER(5)    NOT NULL,
L    NUMBER(5)    NOT NULL,
XL   NUMBER(5)   NOT NULL,
XXL  NUMBER(5)  NOT NULL,
XXXL NUMBER(5) NOT NULL,
EU34 NUMBER(5) NOT NULL,
EU35 NUMBER(5) NOT NULL,
EU36 NUMBER(5) NOT NULL,
EU37 NUMBER(5) NOT NULL,
EU38 NUMBER(5) NOT NULL,
EU39 NUMBER(5) NOT NULL,
EU40 NUMBER(5) NOT NULL,
EU41 NUMBER(5) NOT NULL,
EU42 NUMBER(5) NOT NULL,
EU43 NUMBER(5) NOT NULL,
EU44 NUMBER(5) NOT NULL,
EU45 NUMBER(5) NOT NULL,
EU46 NUMBER(5) NOT NULL,
EU47 NUMBER(5) NOT NULL,
EU48 NUMBER(5) NOT NULL,
EU49 NUMBER(5) NOT NULL
);
CREATE TABLE Client(
ClientId INT PRIMARY KEY IDENTITY(1,1),
ClientFullName VARCHAR(50) NOT NULL,
ClientEmail VARCHAR(50) UNIQUE NOT NULL ,
ClientCI VARCHAR(20) NOT NULL,
ClientPhoneNumber VARCHAR(20) NOT NULL,
ClientDepartament VARCHAR(20) NOT NULL,
ClientCity VARCHAR(20) NOT NULL,
ClientAddressBill VARCHAR(50) NOT NULL,
ClientToHome BIT NOT NULL
);
CREATE TABLE Sale(
SaleId INT PRIMARY KEY IDENTITY(1,1),
SaleAmount DECIMAL NOT NULL,
SaleDate DATETIME DEFAULT GETDATE(),
ClientId INT NOT NULL FOREIGN KEY REFERENCES Client(ClientId)
);
CREATE TABLE Departament(
DepartamentId INT PRIMARY KEY IDENTITY(1,1),
DepartamentName VARCHAR(20) NOT NULL,
DepartamentIsTypeShoes BIT NOT NULL,
DepartamentIsDeleted BIT NOT NULL
);
CREATE TABLE Family(
FamilyId INT PRIMARY KEY IDENTITY(1,1),
FamilyName VARCHAR(20) NOT NULL,
FamilyIsDeleted BIT NOT NULL,
DepartamentId INT NOT NULL FOREIGN KEY REFERENCES Departament(DepartamentId)
);
CREATE TABLE Product(
ProductId INT PRIMARY KEY IDENTITY(1,1),
ProductCode NVARCHAR(10) NOT NULL,
ProductName VARCHAR(20) NOT NULL,
ProductDescription VARCHAR(50) NOT NULL,
ProductImage NVARCHAR(MAX) NOT NULL,
ProductGenre VARCHAR(15) NOT NULL,
ProductColor NVARCHAR(50) NOT NULL,
ProductPrice DECIMAL NOT NULL,
ProductIsDeleted BIT NOT NULL,
StockBySizeId INT NOT NULL FOREIGN KEY REFERENCES StockBySize(StockBySizeId),
FamilyId INT NOT NULL FOREIGN KEY REFERENCES Family(FamilyId)
);
CREATE TABLE LineSale(
LineSaleId INT NOT NULL IDENTITY(1,1),
LineSaleProductQuantity INT NOT NULL,
LineSaleProductPrice DECIMAL NOT NULL,
ProductId INT FOREIGN KEY REFERENCES Product(ProductId),
SaleId INT FOREIGN KEY REFERENCES Sale(SaleId),
primary key(LineSaleId, ProductId, SaleId)
);
